parameters:
    skip_frames: 1
    box_bottom_corner: [12, 13] 
    box_top_corner: [2486, 1488]  
   
    y_t: 4 # yellow light traffic time

    resolutionInPixelsPerMeterX: 0.057  #0.055  #0.056 #84x84 configuration
    resolutionInPixelsPerMeterY: 0.057  #0.055 #0.085

    scaling_factor: 1 # Used to scale the rewards, but for now set to 1.

    local_rewards: True
    waiting_penalty: True
    new_reward: False

    agent_neighbour_combo: {0: [1,4],
                            1: [0, 2, 5],
                            2: [1, 3, 6],
                            3: [2, 7],
                            4: [0, 5],
                            5: [1, 4, 6],
                            6: [2, 5, 7],
                            7: [3, 7]}

    lightPositions: {"0": [[501, 970], [468, 998], [498, 1026], [521, 1002]],
                     "1": [[1001.6, 979], [976, 998], [998, 1026], [1023, 1001]],
                     "2": [[1501, 980], [1482.9, 998], [1498, 1017], [1518, 1001]],
                     "3": [[2002, 980], [1981, 997], [1997.4, 1020], [2021, 1002.7]],
                     "4": [[501.74, 482.36], [484.5, 497], [497.3, 516.4], [515.3, 502.61]],
                     "5": [[1002.8, 483.95], [984.5, 497.6], [997, 515], [1015.4, 502.8]],
                     "6": [[1502.69, 485.28], [1481.3, 498], [1496.9, 519.6], [1517, 502.6]],
                     "7": [[2002.74, 483.56], [1983, 497.4], [1997, 518], [2018.2, 501.51]]}

    factored_coords: {"0": [[12, 530], [1474, 1488]],
                      "1": [[533, 530], [1969.5, 1488]],
                      "2": [[1033, 530], [2486, 1488]],
                      "3": [[12, 13], [1471.3, 971.4]],
                      "4": [[533, 13], [1970, 971.4]],
                      "5": [[1033, 13], [2468, 971.4]],
                      "6": [[12, 13], [972.36, 1488]],
                      "7": [[533, 13], [1474, 1488]],
                      "8": [[1033, 13], [1974, 1488]],
                      "9": [[1533, 13], [2486, 1488]]}

    libsumo: False
    factored_agents: {"0": [0, 1],
                      "1": [1, 2],
                      "2": [2, 3],
                      "3": [4, 5],
                      "4": [5, 6],
                      "5": [6, 7],
                      "6": [0, 4],
                      "7": [1, 5],
                      "8": [2, 6],
                      "9": [3, 7]} 
    # Factored agent number can be a string but make sure that the actual agents represented as a list are input as int as above.

    factored_agent_type: {"0": 'horizontal',
                          "1": 'horizontal',
                          "2": 'horizontal',
                          "3": 'horizontal',
                          "4": 'horizontal',               
                          "5": 'horizontal',
                          "6": 'vertical',
                          "7": 'vertical',
                          "8": 'vertical',
                          "9": 'vertical'}
   
    testmodelnr: {'vertical': 10000}

    seed: 56

    tripinfofolder: 'eight_intersection'

    test: True
    test_seed: [16753, 35821, 9675, 2193, 52120, 70142, 67371, 4470, 78146, 69491, 44398, 66521, 88094, 71935, 90747, 32224, 30813, 15315, 71678, 38054, 6603, 1548, 47881, 81064, 21234, 12045, 47394, 64234, 55742, 76628]  

    generate_conf: True

    tlphasesfile: 'eight.net.xml'
    route_starts: []
    route_ends: []
    route_max_segments: 1
    route_min_segments: 1
    route_segments: ['90 04 415', '154 40 09', '101 15 516', '165 51 110', '112 26 617', '176 62 211', '123 37 718', '187 73 312', '80 01 12 23 313', '133 32 21 10 08', '144 45 56 67 719',
                     '197 76 65 54 414']

    car_pr: 0.4
    car_tm: 3600

    scene: 'eight_intersection'
    env_type: 'SUMO'

    gui: True

    type: 'byCorners'
    speed_dev: 0.0
    verbose: 0
