parameters:
    # Common hyperparameters
    mode: 'train'
    load: false
    name: 'model5_6cars'
    algorithm: PPO
    port: 8000
    gui: false
    env_type: 'SUMO' # 'atari', 'SUMO', or 'gridworld'
    scene: 'loop_network_dumb'
    tlphasesfile: 'sample.net.xml'
    max_steps: 10
    max_episode_steps: 5.0e+3
    frame_height: 14
    frame_width: 14
    num_frames: 1
    skip_frames: 1
    num_epoch: 4
    gamma: 0.99
    lambda: 0.95
    learning_rate: 2.5e-4
    batch_size: 256 # THIS NEEDS TO BE SMALLER THAN n_sequences = memory_size // seq_len
    memory_size: 4096
    train_frequency: 1
    save_frequency: 5.0e+4
    summary_frequency: 1.0e+4
    tensorboard: true
    iteration: -1
    episode: 0

    # SUMO settings
    box_bottom_corner: [9, 13]
    box_top_corner: [65, 69]
    y_t: 6 # Yellow (traffic light) time
    resolutionInPixelsPerMeterX: 0.25
    resolutionInPixelsPerMeterY: 0.25
    car_tm: 6
    state_type: 'ldm_state' # The type of state to use as input for the network. ('bin' (Position Matrix), 'bin_light' (Position Light Matrix), 'value' (Value Matrix))
    scaling_factor: 10
    fast: false
    speed_dev: 0.0 # Can be used to vary the speeds of cars, according to a normal distribution with mean 1 and standard deviation speed_dev (SUMOs default is 0.1)
    car_pr: 1.0
    route_segments: ['L67 L68 L61 L62 L63 L64 L65 L66 L67 L68 L61 L62 L63 L64 L65 L66 L67 L68 L61 L62 L63 L64 L65 L66 L67 L68 L61 L62 L63 L64 L65 L66 L67 L68 L61 L62',
'L63 L64 L65 L66 L67 L68 L61 L62 L63 L64 L65 L66 L67 L68 L61 L62 L63 L64 L65 L66 L67 L68 L61 L62 L63 L64 L65 L66 L67 L68 L61 L62 L63 L64 L65 L66 L67 L68 L61 L62 L63 L64 L65 L66']
    route_starts: []
    route_ends: []
    route_max_segments: 1
    route_min_segments: 1
    local_rewards: True
    waiting_penalty: False
    new_reward: True
    lightPositions: {"0": [[37.5,44.16], [39.2,44.16], [32.5,37.5], [32.5,39.16]]}

    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 1
    num_fc_units: [256]
    # Convolutional module
    convolutional: true
    num_conv_layers: 2
    num_filters: [16, 32]
    kernel_sizes: [4, 2]
    strides: [2, 1]
    # Recurrent module
    recurrent: false
    num_rec_units: 512
    seq_len: 4

    # INFLUENCE MODEL
    influence: false
    inf_box_height: 84
    inf_box_width: 84
    inf_box_center: [[0, 0]]
    inf_frame_height: 84
    inf_frame_width: 84
    inf_num_frames: 1
    inf_num_predictors: 1
    # Influence fully connected module
    inf_num_fc_layers: 0
    inf_num_fc_units: [128]

    # Influence recurrent module
    inf_num_rec_units: 512
    inf_seq_len: 4

    # PPO only
    beta: 5.0e-3
    epsilon: 0.2
    time_horizon: 128
    c1: 0.5
